import { describe, expect, it } from "vitest";
import { departureWithOffset, formSchema, sample, toTripRequest } from "./trip-form";
import { tripPlanSchema } from "./contracts";
import fixture from "@/test/fixtures/trip.json";
import { durationLabel, eventTime } from "./format";

describe("trip request validation", () => {
  it("submits sample coordinates and lets the API infer departure", () => {
    const request = toTripRequest(sample);
    expect(request.current_location).toEqual({
      label: "Chicago, IL",
      lat: 41.8781,
      lng: -87.6298,
    });
    expect(request).not.toHaveProperty("departure");
    expect(request).not.toHaveProperty("start_time");
    expect(request.cycle_used_hours).toBe(34);
  });
  it.each([-1, 70.25, NaN, Infinity])("rejects invalid cycle hours %s", (hours) => {
    expect(formSchema.safeParse({ ...sample, cycle_used_hours: hours }).success).toBe(
      false,
    );
  });
  it.each([0, 69, 70])("accepts cycle boundary %s", (hours) => {
    expect(formSchema.safeParse({ ...sample, cycle_used_hours: hours }).success).toBe(
      true,
    );
  });
  it("rejects identical pickup and delivery but allows current at pickup", () => {
    expect(
      formSchema.safeParse({ ...sample, dropoff_location: sample.pickup_location })
        .success,
    ).toBe(false);
    expect(
      formSchema.safeParse({ ...sample, current_location: sample.pickup_location })
        .success,
    ).toBe(true);
  });
  it("rejects incomplete coordinates and empty labels", () => {
    expect(
      formSchema.safeParse({
        ...sample,
        current_location: { label: "Chicago", lat: 41 },
      }).success,
    ).toBe(false);
    expect(
      formSchema.safeParse({ ...sample, current_location: { label: "  " } }).success,
    ).toBe(false);
  });
  it("preserves a whole-minute offset for a chosen departure", () => {
    const value = departureWithOffset("2026-10-03T08:15");
    expect(value).toMatch(/^2026-10-03T08:15:00[+-]\d{2}:\d{2}$/);
    expect(toTripRequest({ ...sample, departure: "2026-10-03T08:15" }).start_time).toBe(
      value,
    );
    expect(formSchema.safeParse({ ...sample, departure: "not a date" }).success).toBe(
      false,
    );
  });
  it("rejects calendar values normalized into a different day", () => {
    expect(
      formSchema.safeParse({ ...sample, departure: "2026-02-30T08:00" }).success,
    ).toBe(false);
  });
  it("distinguishes same-named places by their selected coordinates", () => {
    expect(
      formSchema.safeParse({
        ...sample,
        pickup_location: { label: "Springfield", lat: 39.78, lng: -89.65 },
        dropoff_location: { label: "Springfield", lat: 37.2, lng: -93.29 },
      }).success,
    ).toBe(true);
  });
});

describe("API contract and display", () => {
  it("accepts the fixture generated by the actual Django serializer", () => {
    const plan = tripPlanSchema.parse(fixture);
    expect(plan.logs).toHaveLength(plan.summary.log_days);
    expect(Object.values(plan.logs[0]!.totals_min).reduce((a, b) => a + b, 0)).toBe(
      1440,
    );
  });
  it("rejects incomplete provider results instead of rendering broken maps", () => {
    expect(
      tripPlanSchema.safeParse({
        ...fixture,
        route: { ...fixture.route, geometry: [[0, 0]] },
      }).success,
    ).toBe(false);
  });
  it("displays the API wall clock without converting to the viewer timezone", () => {
    expect(eventTime("2026-10-03T08:15:00-05:00")).toBe("Oct 3, 8:15 AM · UTC-05:00");
    expect(durationLabel(2040)).toBe("34h");
    expect(durationLabel(90)).toBe("1h 30m");
  });
});
